---
# tasks file for apache2
- include_vars: "{{ ansible_distribution }}.yml"

- import_tasks: install-debian.yml
  when: ansible_distribution == 'debian'

- import_tasks: install-Centos.yml
  when: ansible_distribution == 'CentOS'

- import_tasks: configure.yml

- import_tasks: service.yml
