---
# tasks file for mariadb
- name: 1. install MariaDB server
  yum: 
    name: '{{ item }}'
    state: latest
  with_items:
  - mariadb
  - mariadb-server

- name: 2. Start MariaDB service
  service: name=mariadb state=started enabled=yes

- name: Sets the root password
  mysql_user:
    user: 'root'
    password: "redhat"
    host: 'localhost'
    login_password: "redhat"
    login_user: "root"

- name: added entry in .my.cnf
  copy:
    dest: '/root/.my.cnf'
    content: |
          [client]
          user="root"
          password="redhat"

- name: 3 Create a new DataBase
  mysql_db: name=demo state=present

- name: 4. Create a Database User
  mysql_user: name=demo password=demo priv=*.*:ALL host=localhost state=present

- name: 5a. Copy Sample Data
  copy: src=dump.sql dest=/tmp/dump.sql

- name: 5b. Inser sample Data
  shell: cat /tmp/dump.sql | mysql -u demo -pdemo demo



#check login_user and login_password
