---
- hosts: myhosts
  tasks: 
  - name: Testing When Condition 
    file:
      path: /tmp/Shubham
      state: touch
    when: ansible_distribution == "RedHat"

  - name: Testing When Condition
    file:
      path: /tmp/Agarwal
      state: touch
    when: ansible_distribution == "CentOS"

  - name: Unexpected OS family
    debug:
       msg: OS Distribution "{{ ansible_distribution }}" is mot supported fail=yes
    when: not ansible_distribution == "RedHat" or ansible_distribution == "CentOS"
