---
- hosts: myhosts
  tasks:
  - name: change multiple string
    replace:
       path: /tmp/newfile 
       regexp: '{{ item }}'
       replace: shubham
    with_items:
    - 'is'
    - 'a'
    - 'test'

