---
- hosts: myhosts
  tasks:
  - name: Create Volume Group
    lvg: 
      vg: newvg
      pvs: /dev/sdb1,/dev/sdb2

  - name: Create Logical Volume
    lvol:
      vg: newvg
      lv: newlv
      size: 800M

  - name: Create File System
    filesystem:
      fstype: ext4
      dev: /dev/newvg/newlv

  - name: Mount Logical Volume
    mount:
      name: /lv-ansible
      src: /dev/newvg/newlv
      fstype: ext4
      state: mounted
