---
- hosts: myhosts
  tasks:
  - name: create multiple files with Ansible
    file:
      path: '{{ item }}'
      state: touch
      mode: 0620
    with_items:
    - /tmp/file1
    - /tmp/file2
    - /tmp/file3
    - /tmp/file4
