---
- hosts: myhosts
  tasks:
    - name: make sure selinux is disabled
      lineinfile:
            path: /etc/selinux/config
            regexp: '^SELINUX'
            insertbefore: '^# SELINUXTYPE='
            line: 'SELINUX=disabled'
      register: result
 
    - name: reboot the system
      command: reboot
      when: result.changed
