---
- hosts: myhosts
  tasks:
  - name: install apache
    yum:
      name: httpd
      state: latest

  - name: download remi-repo
    get_url:
       url: http://rpms.remirepo.net/enterprise/remi-release-7.rpm
       dest: /root

  - name: install remi-repo
    yum:
      name: remi-release-7.rpm
      state: installed

  - name: install yum-utils
    yum:
      name: yum-utils
      state: installed

  - name: enable remi-php70
    command:
       yum-config-manager --enable remi-php70

  - name: install php
    yum: 
      name: php
      state: installed

  - name: download phpmyadmin
    get_url:
       url: http://files.phpmyadmin.net/phpMyAdmin/4.7.9/phpMyAdmin-4.7.9-all-languages.tar.gz
       dest: /root

  - name: extract phpmyadmin
    unarchive:
       src: /root/phpMyAdmin-4.7.9-all-languages.tar.gz
       dest: /root

  - name: mv phpmyadmin at /usr/share
    command:
        mv /root/phpMyAdmin-4.7.9-all-languages /usr/share/phpmyadmin

  - name: configure phpmyadmin.conf
    copy:
       dest: /etc/httpd/conf.d/phpmyadmin.conf
       content: |
          Alias /phpmyadmin /usr/share/phpmyadmin
          Alias /phpMyAdmin /usr/share/phpmyadmin


  - name: change httpd.conf
    replace:
        path: /etc/httpd/conf/httpd.conf
        regexp: 'none'
        replace: All

  - name: change httpd.conf
    replace:
        path: /etc/httpd/conf/httpd.conf
        regexp: 'denied'
        replace: granted

  - name: restart apache
    service:
        name: httpd
        state: restarted
