---
- hosts: all
  become: true
  vars:
       doc_root: /var/www/html
  tasks:
     - name: Update yum
       yum: name='*' state=latest

     - name: Install Apache
       yum: name=httpd state=latest

     - name: Create custom document root
       file: path={{ doc_root }} state=directory 

     - name: Set up HTML file
       copy: src=index.html dest={{ doc_root }}/index.html mode=0644

     - name: start httpd
       service: name=httpd state=started enabled=yes
