---
- hosts: myhosts
  tasks:
  - name: create a new text file "shubham"
    file:
      path: '{{ item.location }}'
      state: touch
      mode: '{{ item.mode }}'
      owner: '{{ item.owner }}'
      group: '{{ item.group }}'
    with_items:
    - { location: '/tmp/shubham1',mode: '0222',owner: 'shubhamaa',group: 'root' }
    - { location: '/tmp/shubham2',mode: '0777',owner: 'shubham',group: 'root' }
  - name: insert content in file
    copy:
        content: |
                 This is some
                 not too complex
                 cotent for a file
        dest: /tmp/shubham1
