---
- name: Change ownership of files
  file:
    dest: /var/www/html
    owner: apache
    owner: apache
    recurse: yes

- name: ensure directrioes permission are 0755
  command: 
    find /var/www/html -type d -exec chmod 0755 {} \;

- name: ensure files permission are 0644
  command:
    find /var/www/html -type f -exec chmod 0644 {} \;

  notify:
     restart apache
