---
- hosts: myhosts
  tasks:
  - name: install LAMP
    yum: 
     name: '{{ item }}'
     state: latest
    with_items:
    - httpd
    - mariadb
    - mariadb-server
    - php 
    - php-mysql
    - php-pdo
    - php-gd
    - php-mbstring
    - wget
    - MySQL-python

  - name: start service
    service:
      name: '{{ item.name }}'
      state: '{{ item.state }}'
      enabled: '{{ item.enabled }}'
    with_items:
    - { name: 'httpd', state: 'started', enabled: 'yes' }
    - { name: 'mariadb', state: 'started', enabled: 'yes' }
