---
- name: install packages for DB
  yum:
    name: '{{ item }}'
    state: latest
  with_items:
  - mariadb
  - mariadb-server
  - php
  - php-mysql
  - php-pdo
  - php-gd
  - php-mbstring
  - wget
  - MySQL-python
