---
- hosts: localhost
  vars:
      instance_type: t2.micro
      security_group: webserver # Change the security group name here
      image: ami-0b1e356e # This is an AMI i created myself
      keypair: shubh-key-pair # This is one of my keys that i already have in AWS
      region: us-east-2  # Change the Region
      count: 1
  tasks:

      - name: Create a security group
        ec2_group:
            name: "{{ security_group }}"
            description: Security Group for webserver Servers
            region: "{{ region }}"
            aws_secret_key: "esju85/StSMI9DyKbgl4n+mPBaH1iJ0qxQ0qjEZQ"
            aws_access_key: "AKIAJQBMWSHPPGDE36LQ"
            rules:
             - proto: tcp
               from_port: 22
               to_port: 22
               cidr_ip: 0.0.0.0/0
             - proto: tcp
               from_port: 80
               to_port: 80
               cidr_ip: 0.0.0.0/0
             - proto: tcp
               from_port: 443
               to_port: 443
               cidr_ip: 0.0.0.0/0
            rules_egress:
             - proto: all
               cidr_ip: 0.0.0.0/0

      - name: Launch the new EC2 Instance
        ec2:
            group: "{{ security_group }}"
            instance_type: "{{ instance_type}}" 
            image: "{{ image }}"
            wait: yes 
            region: "{{ region }}"
            keypair: "{{ keypair }}"
            count: "{{count}}"
            aws_secret_key: "esju85/StSMI9DyKbgl4n+mPBaH1iJ0qxQ0qjEZQ"
            aws_access_key: "AKIAJQBMWSHPPGDE36LQ"
        register: ec2_out

      - name: Add the newly created EC2 instance(s) to the local host group (located inside the directory)
        lineinfile:
             dest: "./hosts" 
             regexp: "{{ item.public_ip }}"
             insertafter: "[webserver]"
             line: "{{ item.public_ip }}"
        with_items: "{{ ec2_out.instances }}"


      - name: Wait for SSH to come up
        wait_for:
            host: "{{ item.public_ip }}"
            port: 22 
            state: started
        with_items: "{{ ec2_out.instances }}"

      - name: Add tag to Instance(s)
        ec2_tag: 
          resource: "{{ item.id }}"
          region: "{{ region }}"
          state: "present"
          aws_secret_key: "esju85/StSMI9DyKbgl4n+mPBaH1iJ0qxQ0qjEZQ"
          aws_access_key: "AKIAJQBMWSHPPGDE36LQ"
        with_items: "{{ ec2_out.instances }}"
        args:
          tags:
            Name: webserver
